'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblBipannaInsuree
    Public Property BipannaInsureeID As Integer
    Public Property RowID As Byte()
    Public Property InsureeID As Integer
    Public Property RelativeName As String
    Public Property Relationship As Nullable(Of Short)
    Public Property Religion As String
    Public Property HospitalOpdIpdNoYear As String
    Public Property HospitalBipannaNo As String
    Public Property DistrictPubLetterDate As Nullable(Of Date)
    Public Property DistrictPubLetterNo As String
    Public Property Disease As String
    Public Property CancerType As String
    Public Property PhotoID As Nullable(Of Integer)
    Public Property ValidityFrom As Date
    Public Property ValidityTo As Nullable(Of Date)
    Public Property BipannaInsureeUUID As System.Guid

    Public Overridable Property tblInsuree As tblInsuree
    Public Overridable Property tblPhotos As tblPhotos
    Public Overridable Property tblRelations As tblRelations

End Class
